Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.define "vm1" do |vm1|
    vm1.vm.host_name = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.61", netmask: "255.255.255.128"
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.host_name = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.62", netmask: "255.255.255.192" 
  end
  config.vm.define "vm3" do |vm3|
    vm3.vm.host_name = "vm3"
    vm3.vm.network "private_network", ip: "192.168.56.65", netmask: "255.255.255.192" 
  end
end
