Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.define "vm1" do |vm1|
    vm1.vm.host_name = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.62"
    vm1.vm.provision "shell", path: "provision-vm1.sh"
  end  
  config.vm.define "vm2" do |vm2|
    vm2.vm.host_name = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.61"
    vm2.vm.network "private_network", ip: "192.168.57.61"
  end  
  config.vm.define "vm3" do |vm3|
    vm3.vm.host_name = "vm3"
    vm3.vm.network "private_network", ip: "192.168.57.62"
    vm3.vm.provision "shell", path: "provision-vm3.sh"
  end  
end
