Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", path: "provision.sh"
  config.vm.define "server" do |server|
    server.vm.host_name = "server"
    server.vm.network "private_network", ip: "192.168.56.180"
  end  
  config.vm.define "client" do |client|
    client.vm.host_name = "client"
    client.vm.network "private_network", ip: "192.168.56.181"
  end  
end



